<a href="https://colab.research.google.com/github/GallardoCarmen/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [4]:
2 in lista

True

In [5]:
35 in lista

False

In [6]:
lista[0]

5

In [7]:
lista[-1]

54

In [8]:
lista[2:4]

[9, 8]

In [9]:
lista[:5]

[5, 6, 9, 8, 7]

In [10]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [11]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [12]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [14]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
len(a)

4

In [16]:
min(a)

1

In [17]:
max(a)

4

In [18]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [19]:
b[0]

array([1, 2, 3])

In [20]:
b[:,1]

array([2, 6, 5])

In [21]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [22]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [23]:
a = np.random.rand(5,5)
a

array([[0.69926341, 0.13386408, 0.38435812, 0.75728293, 0.3016027 ],
       [0.29431417, 0.90446132, 0.39955695, 0.93126065, 0.23914506],
       [0.71335076, 0.39854296, 0.08198749, 0.06834118, 0.70154709],
       [0.08816034, 0.87204557, 0.41628676, 0.3865479 , 0.99737125],
       [0.79361672, 0.58850414, 0.1962967 , 0.47719501, 0.83007965]])

In [24]:
a.shape

(5, 5)

In [25]:
b  = np.random.rand(5,5)
b

array([[0.15001822, 0.3758324 , 0.0521669 , 0.79169765, 0.42634474],
       [0.63844836, 0.31435967, 0.65928595, 0.0205019 , 0.7187771 ],
       [0.02220827, 0.90347721, 0.29928464, 0.06148565, 0.18827595],
       [0.62626419, 0.93834542, 0.13343355, 0.04900439, 0.67365118],
       [0.92049545, 0.1529136 , 0.5897077 , 0.87379505, 0.65175503]])

In [26]:
a + b

array([[0.84928163, 0.50969648, 0.43652502, 1.54898058, 0.72794744],
       [0.93276254, 1.21882099, 1.0588429 , 0.95176255, 0.95792216],
       [0.73555903, 1.30202018, 0.38127213, 0.12982683, 0.88982304],
       [0.71442453, 1.81039099, 0.54972031, 0.4355523 , 1.67102243],
       [1.71411217, 0.74141774, 0.7860044 , 1.35099007, 1.48183468]])

In [27]:
a-b

array([[ 0.54924519, -0.24196833,  0.33219122, -0.03441471, -0.12474204],
       [-0.34413419,  0.59010165, -0.25972901,  0.91075876, -0.47963205],
       [ 0.69114249, -0.50493425, -0.21729715,  0.00685552,  0.51327115],
       [-0.53810385, -0.06629985,  0.28285321,  0.33754351,  0.32372007],
       [-0.12687874,  0.43559054, -0.393411  , -0.39660004,  0.17832462]])

In [28]:
a*b

array([[0.10490225, 0.05031046, 0.02005077, 0.59953911, 0.12858673],
       [0.1879044 , 0.28432616, 0.26342228, 0.01909261, 0.17189199],
       [0.01584229, 0.36007449, 0.0245376 , 0.004202  , 0.13208444],
       [0.05521167, 0.81827996, 0.05554662, 0.01894255, 0.67188032],
       [0.73052058, 0.08999028, 0.11575768, 0.41697064, 0.54100859]])

In [29]:
a/b

array([[ 4.66118987,  0.35618024,  7.36785441,  0.95653048,  0.70741509],
       [ 0.46098352,  2.87715442,  0.60604499, 45.42314921,  0.33271101],
       [32.12095008,  0.44112121,  0.27394486,  1.11149794,  3.72616418],
       [ 0.14077181,  0.92934388,  3.11980571,  7.8880254 ,  1.48054553],
       [ 0.86216256,  3.84860569,  0.33287118,  0.54611778,  1.27360681]])

In [30]:
np.transpose(a)

array([[0.69926341, 0.29431417, 0.71335076, 0.08816034, 0.79361672],
       [0.13386408, 0.90446132, 0.39854296, 0.87204557, 0.58850414],
       [0.38435812, 0.39955695, 0.08198749, 0.41628676, 0.1962967 ],
       [0.75728293, 0.93126065, 0.06834118, 0.3865479 , 0.47719501],
       [0.3016027 , 0.23914506, 0.70154709, 0.99737125, 0.83007965]])

In [31]:
1/a

array([[ 1.43007627,  7.47026406,  2.60174027,  1.32051042,  3.31562014],
       [ 3.39772965,  1.10563048,  2.50277215,  1.07381322,  4.18156246],
       [ 1.4018349 ,  2.50913977, 12.19698291, 14.63246681,  1.42542106],
       [11.34296855,  1.14672907,  2.40219026,  2.58700147,  1.00263568],
       [ 1.2600541 ,  1.69922339,  5.09432916,  2.09557931,  1.20470367]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [4]:
import numpy as np

def suma_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ

  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LA MISMA DIMENSIÓN
  if A.shape != B.shape:
    print("Las matrices A y B deben tener la misma dimensión")
    return None
  suma = np.zeros_like(A)
  #Suma elemento a elemento
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      suma[i, j] = A[i, j] + B[i, j]

  return suma

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [9]:
import numpy as np

def transpuesta(A):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  f, c = A.shape
  transpuestaA = np.zeros((c, f) )
  #Calcula la transpuesta
  for i in range(f):
    for j in range(c):
      transpuestaA[j, i] = A[i, j]

  return transpuestaA

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [11]:
import numpy as np

def multiplicar_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LAS DIMENSIONES
  # ADECUADAS QUE PERMITEN LA MULTIPLICACIÓN MATRICIAL

  fA, cA = A.shape
  fB, cB = B.shape

  if cA != cB:
    print("Las dimensiones de las matrices no son adecuadas")
    return None

  result = np.zeros((fA, cB))

  # Realiza la multiplicación manualmente
  for i in range(fA):
      for j in range(cB):
          for k in range(cA):
              result[i, j] += A[i, k] * B[k, j]

  return result

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))